# Generated by Django 3.1.4 on 2020-12-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        ('couches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Couch',
        ),
    ]
