# Generated by Django 3.1.4 on 2020-12-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couches', '0002_auto_20201221_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couch',
            old_name='state',
            new_name='division',
        ),
    ]
